### ISSUE TITLE
Is shuttle tied to Rocket, or are other servers possible?

### ISSUE THREAD

**Issue by mikeando** [getsynth/shuttle#73]
The initial paragarph doesn't mention Rocket, but all the examples use it, and it is not clear if we can use another server architecture.
Even if it is not yet supported, but is intended to be supported, it would be good to hear about it.

**Comment by brokad** [comment]
Indeed! We chose Rocket as a first supported target because we were familiar with it. The key is the [IntoService](https://docs.rs/shuttle-service/0.2.4/shuttle_service/trait.IntoService.html) trait, not the web framework specifically.

We're already working on implementing support for axum #83!

**Comment by christoshadjiaslanis** [comment]
Axum is done! And Tide is in the roadmap. Closing this issue for now!
